### ISSUE TITLE
Container crashes on Start (Docker API has failed)

### ISSUE THREAD

**Issue by truthsword** [draganczukp/url#6] opened 2020-09-18 22:30 UTC
Updated to the most recent version today "latest". 

Container won't start...

Error message
![](https://i.imgur.com/tCIpdzZ.png)

**Comment by draganczukp** [comment] 2020-09-19 07:09
I tried to reproduce this on my machine and on my server and it seems to work fine. I'll need you to answer some questions

1. What OS (and what version) are you using?
2. What's the output of `docker -v`?
3. Are you using `docker run` or `docker-compose`?
4.1. (for `docker run`) What's the exact command you use?
4.2. (for `docker-compose`) What's in your `docker-compose.yml`?
5. Have you tried running 1.0 instead of latest?
6. Was it working before? If it did, when was the last update you did (before this one of course)?

**Comment by truthsword** [comment] 2020-09-19 15:50
> What OS (and what version) are you using?

Synology DSM v6.2.3

> What's the output of docker -v?

Docker version 18.09.8, build bfed4f5

> Are you using docker run or docker-compose?

Docker run

> (for docker run) What's the exact command you use?

Launch container directly from either Synology Docker GUI or Portainer Docker container.

> Have you tried running 1.0 instead of latest?

I generally stick with "latest" with the understanding that it infers "latest stable". Also... it simplifies updating since the tag is constant.

> Was it working before? If it did, when was the last update you did (before this one of course)?

Yes, just fine. I'm using this image successfully...

![](https://i.imgur.com/I3iFC3i.png)

**Comment by draganczukp** [comment] 2020-09-19 17:42
Can you try using a specific tag, like 1.0 or 1.1? This will tell me if the issue is the latest image you have, or if it's something with your docker installation.

I never used Synology, and the docker version is one major version behind (I have `Docker version 19.03.12-ce` on my server). It's possible that this has something to do with this error, though it shouldn't given that it was working before.

> Launch container directly from either Synology Docker GUI or Portainer Docker container

Can you maybe try running `docker run --rm draganczukp/simplyshorten:latest` in a shell? This will most likely throw a NullPointerException, since this command doesn't set any environment variables.

What's weird to me is that since the release of 1.0 I didn't touch the Dockerfile, and the first change to actual code happened today as part of #5. The only thing I can think of that would have any effect on you would be if the container somehow got corrupted or didn't build correctly.

**Comment by truthsword** [comment] 2020-09-19 18:01
1.1 is running. The logs showed this...

![](https://i.imgur.com/iAdTWI7.png)

Shortening seems fine. I have it running off my local LAN IP, so I will shut down and retag the 1.1 image with "latest" and restart to launch it with my domain name/settings.

**Comment by truthsword** [comment] 2020-09-19 18:15
OK... all seems well now. I redid the container downloading "latest" (I presume this is 1.1) from scratch and no issues.

**Comment by draganczukp** [comment] 2020-09-19 18:36
Glad it's working now. It seems like the image got corrupted somewhere.

Since it's working I'm closing this issue.

**Closed as completed by draganczukp** 2020-09-19 18:36 UTC
Labels: bug, cannot-reproduce
